### PR TITLE
updated elm-test dependencies to the current version range

### PR DESCRIPTION
**Pull request by CarstenKoenig**

### CODE REVIEW

**Comment by dpinn** [comment]
Carsten did this in response to my conversation on elmlang.slack.com about a dependency problem I came across. I wanted to use elm-test in my project, but it conflicted with the elm-test dependency published by elm-dialog. I wonder if the test directory could have its own `elm-package.json` with the elm-test dependency, and then the elm-test dependency could be removed from the main `elm-package.json` entirely.

**Comment by CarstenKoenig** [comment]
the `elm-test` situation is a bit strange right now but as far as I can see `elm-test tests\StateTest.elm` succeeds locally but I have no clue if it correctly did setup the `makefile` (Travis CI is really busy with downloading elm-make dependencies right now)

**Comment by CarstenKoenig** [comment]
oh well 

```
/home/travis/.nvm/v0.10.36/lib/node_modules/elm-test/node_modules/firstline/firstline.js:6
  return new Promise(function (resolve, reject) {
             ^
ReferenceError: Promise is not defined
```

I have no clue how to fix this - I hope someone can help.

Sorry

**Comment by CarstenKoenig** [comment]
npm

**Comment by CarstenKoenig** [comment]
no problem - thanks for the answer

----

btw: as you can see the changes are minor - thankfully there was only one test ;)

**Comment by dpinn** [comment]
I've changed my elm-dialog dependency to 4.0.1 and all is well. I'm back up and running. Thank you Kris and Carsten for helping me.

**Pull request closed without merging**
