### PR TITLE
Add Sizing of Dialogs and Fix #5

### LINKED ISSUE #5: Big Dialog is outside screen and unreachable
Displaying a lot of information in a dialog e.g. a huge table can grow the size of the Dialog bigger than the actual screen.

The problem is that no scrollbars or similar appear to be able to see/access all the content of the dialog.

### PR DESCRIPTION
**Pull request by bwegh**
I need both, large dialogs in width, so I introduce the DialogSize
and I added the overflow styles, to fix my issue #5

### CODE REVIEW

**Comment by sjalowoi** [comment]
Hi  krisajenkins, 

Thanks for your good job with elm-dialog, it is really helpful. I need the change  from bwegh (thanks!), i would like to know if you will  accept the pullrequest in soon or if i need to integrate this change in my project?

Best regards
Sylvain

**Comment by bwegh** [comment]
a pity this has not been included before upgrading to 0.18

**Comment by bwegh** [comment]
please have a look again and eventually accept this PR, thanks in advance

**Comment by jankowskirobert** [comment]
ping, How is the situation?

**Pull request closed without merging**
